spring:
  application:
    name: 100-Books-And-More
  datasource:
    url: "jdbc:postgresql://localhost:5432/books"
    username: "admin"
    password: "root123"
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:/db/migration
    enabled: true
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
